import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
const fs = require("fs");

export default defineConfig(({ command, mode }) => {
  if (command === "serve") {
    return {
      define: { "process.env": {} },
      plugins: [react()],
      server: {
        port: 3000,
        host: "0.0.0.0",
        timing: false,
        https: {
          // these files are generated by running the above shell script
          key: fs.readFileSync("/etc/letsencrypt/live/fergl.ie/privkey.pem"),
          cert: fs.readFileSync("/etc/letsencrypt/live/fergl.ie/cert.pem"),
        },
      },
    };
  } else {
    return { define: { "process.env": {} }, plugins: [react()] };
  }
});
