import {
  CirclePlus,
  BellDot,
  ChevronDown,
  ChevronUp,
  LucideIcon,
  Eye,
  Mail,
  Search,
  Rocket,
  LogIn,
  Key,
  Play,
  PlayCircle,
  PersonStanding,
  Airplay,
  Cast,
  Copy,
  Disc,
  SwatchBook,
} from "lucide-react";

export type Icon = LucideIcon;
export const Icons = {
  add: CirclePlus,
  airplay: Airplay,
  alarm: BellDot,
  avatar: PersonStanding,
  cast: Cast,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  colorSwatch: SwatchBook,
  copy: Copy,
  eye: Eye,
  key: Key,
  login: LogIn,
  mail: Mail,
  play: Play,
  playCircle: PlayCircle,
  search: Search,
  record: Disc,
  rocket: Rocket,
};
